apiVersion: v1
kind: Service
metadata:
  name: microservices-service
  labels:
    app: microservices
spec:
  type: LoadBalancer
  selector:
    app: microservices
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080